// review-data.js — the authenticated findings index for /review/.
//
// R2b (SOMA/specs/handshake-protocol-v1.md): a report card's bare count is a
// named anti-pattern with no path to the detail. This is that path — but the
// findings name internals (fix mechanisms, before/after screenshots), so
// they sit behind the SAME owner gate as the board, enforced here server-side
// (not just by client JS): verify the caller's Supabase access token, require
// an allowlisted Mike identity, only then return the data. An anonymous or
// wrong-account request gets 401/403 and nothing else, same failure shape as
// pulse-agent-session.js (the existing precedent for this exact pattern).
//
// findings.json is generated by review/build-findings.py from the review
// markdown files and lives co-located in this directory (never under
// public/), so it is never reachable as a static file.
//
// NOTE: the data folder is named review-data-FILES (not review-data) on
// purpose — Netlify's esbuild function bundler mis-resolves a directory
// import when a co-located folder shares this function file's exact
// basename (`review-data.js` + `review-data/` => "Directory import
// '/var/task/review-data' is not supported ... Did you mean
// '/var/task/review-data.js'?", live-reproduced 2026-08-15). Any basename
// that doesn't collide works; keep this one distinct if renaming.
const findings = require('./review-data-files/findings.json');

const SUPABASE_URL = 'https://omfwcodoimjmbrhssvfl.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_vi2qDWjozUJ5mi9dwirkLA_rj6UaqLf';
// Mirror of public.is_pulse_owner() / OWNER_EMAILS in public/index.html and
// public/review/index.html. Keep all three in sync.
const ALLOWED_EMAILS = ['mw@mike-wolf.com', 'mw.personalmail@gmail.com'];

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Content-Type': 'application/json',
  'Cache-Control': 'no-store',
};

function response(statusCode, body) {
  return { statusCode, headers: cors, body: JSON.stringify(body) };
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: { ...cors, 'Access-Control-Allow-Methods': 'GET, OPTIONS' }, body: '' };
  }
  if (event.httpMethod !== 'GET') {
    return response(405, { error: 'GET only' });
  }

  const authHeader = event.headers.authorization || event.headers.Authorization || '';
  if (!authHeader.startsWith('Bearer ')) {
    return response(401, { error: 'Sign in to Pulse first.' });
  }

  try {
    const userResponse = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
      headers: { apikey: SUPABASE_ANON_KEY, Authorization: authHeader },
    });
    if (!userResponse.ok) {
      return response(401, { error: 'Your Pulse session has expired.' });
    }
    const user = await userResponse.json();
    if (!ALLOWED_EMAILS.includes((user.email || '').toLowerCase())) {
      return response(403, { error: 'This board is private.' });
    }
    return response(200, findings);
  } catch (_) {
    return response(502, { error: 'Findings temporarily unavailable.' });
  }
};
