// review-asset.js — authenticated streaming of the review's before/after
// screenshots (same owner gate as review-data.js / the board itself).
//
// Screenshots are never under public/ — they're base64-encoded in
// review-assets/manifest.json (generated by review/build-findings.py) and
// require an owner-verified Supabase bearer token to be returned at all.
// `?path=` is checked against an exact-key allowlist (the manifest itself) —
// no path traversal, no arbitrary-file read.
const manifest = require('./review-assets/manifest.json');

const SUPABASE_URL = 'https://omfwcodoimjmbrhssvfl.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_vi2qDWjozUJ5mi9dwirkLA_rj6UaqLf';
const ALLOWED_EMAILS = ['mw@mike-wolf.com', 'mw.personalmail@gmail.com'];

const jsonHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Content-Type': 'application/json',
  'Cache-Control': 'no-store',
};

function errorResponse(statusCode, body) {
  return { statusCode, headers: jsonHeaders, body: JSON.stringify(body) };
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: { ...jsonHeaders, 'Access-Control-Allow-Methods': 'GET, OPTIONS' }, body: '' };
  }
  if (event.httpMethod !== 'GET') {
    return errorResponse(405, { error: 'GET only' });
  }

  const authHeader = event.headers.authorization || event.headers.Authorization || '';
  if (!authHeader.startsWith('Bearer ')) {
    return errorResponse(401, { error: 'Sign in to Pulse first.' });
  }

  // Verify identity BEFORE touching the manifest at all — a bearer-shaped
  // header with a garbage token must not be able to probe which filenames
  // exist. Path-existence is only checked once the caller is a proven owner.
  try {
    const userResponse = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
      headers: { apikey: SUPABASE_ANON_KEY, Authorization: authHeader },
    });
    if (!userResponse.ok) {
      return errorResponse(401, { error: 'Your Pulse session has expired.' });
    }
    const user = await userResponse.json();
    if (!ALLOWED_EMAILS.includes((user.email || '').toLowerCase())) {
      return errorResponse(403, { error: 'This board is private.' });
    }

    const path = (event.queryStringParameters || {}).path || '';
    if (!Object.prototype.hasOwnProperty.call(manifest, path)) {
      return errorResponse(404, { error: 'Unknown asset.' });
    }

    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Content-Type': 'image/png',
        'Cache-Control': 'private, max-age=3600',
      },
      body: manifest[path],
      isBase64Encoded: true,
    };
  } catch (_) {
    return errorResponse(502, { error: 'Asset temporarily unavailable.' });
  }
};
