-- Minimal, Supabase-faithful replica of the live objects the lockdown
-- migration touches (shapes copied from omfwcodoimjmbrhssvfl on 2026-09-19).
-- Used by run.sh; never applied to a real project.
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create schema auth;
grant usage on schema auth to anon, authenticated, service_role;
create function auth.jwt() returns jsonb language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claim', true), ''),
                  nullif(current_setting('request.jwt.claims', true), ''))::jsonb
$$;
create function auth.role() returns text language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claim.role', true), ''),
                  (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role'))::text
$$;

grant usage on schema public to anon, authenticated, service_role;

create function public.is_pulse_owner() returns boolean language sql stable as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) in ('mw@mike-wolf.com', 'mw.personalmail@gmail.com');
$$;

create table public.pulse_cards (
  id uuid primary key default gen_random_uuid(),
  app_id text not null default 'pulse-zero',
  type text not null default 'action',
  payload jsonb not null default '{}',
  status text not null default 'open',
  created_at timestamptz not null default now()
);
alter table public.pulse_cards enable row level security;
create policy pulse_cards_mike_select on public.pulse_cards for select using (public.is_pulse_owner());
create policy pulse_cards_service_role_all on public.pulse_cards for all
  using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
grant all on public.pulse_cards to authenticated, service_role;

create table public.mac_commands (
  id bigint generated by default as identity primary key,
  command text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  executed_at timestamptz,
  result jsonb,
  pulse_card_id uuid references public.pulse_cards(id) on delete set null,
  pulse_action_id text,
  pulse_revision integer,
  attempt integer,
  idempotency_key text
);
create unique index mac_commands_idempotency_key_unique on public.mac_commands (idempotency_key)
  where idempotency_key is not null;
alter table public.mac_commands enable row level security;
-- The live pre-migration policy.
create policy mw_read_write on public.mac_commands for all
  using (public.is_pulse_owner()) with check (public.is_pulse_owner());
grant insert, select, update, delete, truncate, references, trigger on public.mac_commands to authenticated, service_role;
grant usage on all sequences in schema public to authenticated, service_role;
