-- Minimal, Supabase-faithful replica of the live objects the provenance
-- migration touches (shapes copied from omfwcodoimjmbrhssvfl on 2026-09-22).
-- Used by run.sh; never applied to a real project.
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create schema auth;
grant usage on schema auth to anon, authenticated, service_role;
create function auth.jwt() returns jsonb language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claim', true), ''),
                  nullif(current_setting('request.jwt.claims', true), ''))::jsonb
$$;
create function auth.role() returns text language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claim.role', true), ''),
                  (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role'))::text
$$;

grant usage on schema public to anon, authenticated, service_role;

create function public.is_pulse_owner() returns boolean language sql stable as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) in ('mw@mike-wolf.com', 'mw.personalmail@gmail.com');
$$;

create table public.pulse_cards (
  id uuid primary key default gen_random_uuid(),
  app_id text not null default 'pulse-zero',
  type text not null default 'action',
  payload jsonb not null default '{}',
  status text not null default 'open',
  answer jsonb,
  answered_at timestamptz,
  dedupe_key text,
  created_by text,
  created_at timestamptz not null default now()
);
alter table public.pulse_cards enable row level security;
create policy pulse_cards_mike_select on public.pulse_cards for select using (public.is_pulse_owner());
create policy pulse_cards_mike_update on public.pulse_cards for update
  using (public.is_pulse_owner()) with check (public.is_pulse_owner());
create policy pulse_cards_service_role_all on public.pulse_cards for all
  using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
grant all on public.pulse_cards to authenticated, service_role;

-- The live pre-migration comments table and its policies.
create table public.pulse_card_comments (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.pulse_cards(id) on delete cascade,
  author text not null default 'mike',
  body text not null,
  created_at timestamptz not null default now()
);
alter table public.pulse_card_comments enable row level security;
create policy pulse_card_comments_service_role_all on public.pulse_card_comments for all
  using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
-- Live shape since 20260727_google_signin_owner_emails.sql: is_pulse_owner(),
-- NOT the literal address, so Mike's Google identity works too.
create policy pulse_card_comments_mike_select on public.pulse_card_comments for select
  using (public.is_pulse_owner());
create policy pulse_card_comments_mike_insert on public.pulse_card_comments for insert
  with check (public.is_pulse_owner());
grant all on public.pulse_card_comments to authenticated, service_role;

-- The webhook notify functions the migration replaces. The replica has no
-- pg_net or vault, so these stand in with an observable side effect: a row in
-- public.webhook_calls for every fire. That is what the cases assert on --
-- "did a forged row reach the Netlify function" is the whole question.
create table public.webhook_calls (
  id bigint generated by default as identity primary key,
  hook text not null,
  row_id text not null,
  author text,
  status text
);
grant all on public.webhook_calls to authenticated, service_role;
grant usage on all sequences in schema public to authenticated, service_role;

create schema if not exists vault;
create table vault.decrypted_secrets (name text, decrypted_secret text);
insert into vault.decrypted_secrets values ('pulse_webhook_secret', 'replica-secret');

create schema if not exists extensions;
create schema if not exists net;
-- Stand-in for net.http_post: records the call instead of making it.
create function net.http_post(url text, headers jsonb default '{}', body jsonb default '{}')
returns bigint language plpgsql security definer as $$
begin
  insert into public.webhook_calls(hook, row_id, author, status)
  values (url, coalesce(body ->> 'comment_id', body ->> 'card_id', '?'),
          body ->> 'author', body ->> 'status');
  return 1;
end;
$$;

-- Pre-migration function/trigger bodies, copied from the live migrations
-- 20260726b and 20260817, so the test proves the REPLACEMENT changes behavior.
create or replace function public.notify_card_comment_insert()
returns trigger language plpgsql security definer
set search_path = public, extensions, vault, net as $fn$
declare secret text;
begin
  select decrypted_secret into secret from vault.decrypted_secrets
    where name = 'pulse_webhook_secret' limit 1;
  if secret is not null then
    perform net.http_post(
      url := 'https://pulse-zero.netlify.app/.netlify/functions/card-comment-webhook',
      headers := jsonb_build_object('x-pulse-secret', secret),
      body := jsonb_build_object('comment_id', new.id, 'card_id', new.card_id, 'author', new.author));
  end if;
  return new;
end;
$fn$;
create trigger pulse_card_comments_notify after insert on public.pulse_card_comments
  for each row execute function public.notify_card_comment_insert();

create or replace function public.notify_card_answer_update()
returns trigger language plpgsql security definer
set search_path = public, extensions, vault, net as $fn$
declare secret text;
begin
  if new.status = old.status then return new; end if;
  if new.status not in ('answered', 'resolved', 'retired', 'bounced') then return new; end if;
  select decrypted_secret into secret from vault.decrypted_secrets
    where name = 'pulse_webhook_secret' limit 1;
  if secret is not null then
    perform net.http_post(
      url := 'https://pulse-zero.netlify.app/.netlify/functions/card-answer-webhook',
      headers := jsonb_build_object('x-pulse-secret', secret),
      body := jsonb_build_object('card_id', new.id, 'status', new.status));
  end if;
  return new;
end;
$fn$;
create trigger pulse_cards_answer_notify after update on public.pulse_cards
  for each row execute function public.notify_card_answer_update();
