-- Pulse Zero executable queue v1 (additive, feature flagged)
--
-- SUPERSEDED 2026-08-16 (frictionless-console-v1 / WQ-301 Slice 1, Mike-ratified
-- card 913e36c5-7253-4341-a0a3-b45e499f554f). Never apply the unflagged
-- statement triggers described below — they fire on every INSERT/UPDATE on
-- pulse_cards including legacy producers (fact 1 just below), which is exactly
-- the blast radius frictionless-console-v1.md §4 flags as deferred, not
-- adopted. The pieces worth salvaging later (the enqueue RPC + gate taxonomy)
-- are noted in that spec's §4; this file stays as a reference artifact only.
--
-- This migration is intentionally an artifact only in this change. Do not run it
-- against the shared project without a backup, shadow-ranking review, and Mike's
-- explicit migration approval. Existing rows default to queue_state=legacy and
-- therefore cannot enter the new active projection.
--
-- Two operational facts the approver must know:
-- 1. Reads are feature-flagged, WRITES ARE NOT: once applied, every
--    INSERT/UPDATE on pulse_cards — legacy producers included — fires the
--    statement triggers below, serializes on one advisory lock, and runs a
--    full reconcile. A reconcile failure aborts unrelated card pushes.
-- 2. Executed once end-to-end on 2026-08-01 against a local supabase/postgres
--    15.8 shadow DB (base schema reconstructed from README §Schema + all four
--    prior migrations): applies cleanly, re-applies idempotently, and the
--    github_accept_org_invite insert->reconcile->enqueue (idempotent retry)
--    and decision insert->answer->acknowledge->resolved paths all pass.
--    That run caught and fixed two runtime-only bugs the JS test suite
--    (which only pattern-matches this file's text) could not:
--    jsonb_object_length() does not exist, and reconcile_pulse_queue's
--    out-params shadowed its own column references. Still re-verify against
--    a Supabase branch DB before the shared project.

alter table public.pulse_cards
  add column if not exists contract_version smallint,
  add column if not exists gate_contract jsonb,
  add column if not exists continuation_contract jsonb,
  add column if not exists queue_state text not null default 'legacy',
  add column if not exists queue_position smallint,
  add column if not exists priority_band smallint,
  add column if not exists priority_reason text,
  add column if not exists deadline_at timestamptz,
  add column if not exists blocked_work_count integer not null default 1,
  add column if not exists mission_lane text,
  add column if not exists eligible_at timestamptz,
  add column if not exists contract_hash text,
  add column if not exists eligibility_errors jsonb not null default '[]'::jsonb;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'pulse_queue_state_check') then
    alter table public.pulse_cards add constraint pulse_queue_state_check
      check (queue_state in ('legacy', 'intake', 'eligible', 'queued', 'hold'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pulse_queue_position_check') then
    alter table public.pulse_cards add constraint pulse_queue_position_check
      check (queue_position is null or queue_position between 1 and 5);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pulse_priority_band_check') then
    alter table public.pulse_cards add constraint pulse_priority_band_check
      check (priority_band is null or priority_band between 0 and 3);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pulse_blocked_work_count_check') then
    alter table public.pulse_cards add constraint pulse_blocked_work_count_check
      check (blocked_work_count >= 0);
  end if;
end;
$$;

create unique index if not exists pulse_one_card_per_queue_position
  on public.pulse_cards (app_id, queue_position)
  where queue_state = 'queued' and queue_position is not null;

create table if not exists public.pulse_queue_events (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.pulse_cards(id) on delete cascade,
  event_type text not null,
  from_state text,
  to_state text,
  from_position smallint,
  to_position smallint,
  reason jsonb not null default '{}'::jsonb,
  actor text not null default 'queue_reconciler',
  contract_hash text,
  created_at timestamptz not null default now()
);

create index if not exists pulse_queue_events_card_created
  on public.pulse_queue_events (card_id, created_at desc);

-- Verified action completion starts a durable return-to-owner run. The browser
-- can create/read one through narrow RPCs, but cannot mark it successful.
create table if not exists public.pulse_continuation_runs (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.pulse_cards(id) on delete cascade,
  command_id bigint references public.mac_commands(id) on delete restrict,
  owner_ref text not null,
  correlation_key text not null,
  verifier_kind text not null,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'verifying', 'succeeded', 'failed')),
  safe_message text,
  verification_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (card_id, command_id)
);

create unique index if not exists pulse_one_direct_continuation_per_card
  on public.pulse_continuation_runs (card_id)
  where command_id is null;

alter table public.pulse_queue_events enable row level security;
alter table public.pulse_continuation_runs enable row level security;

drop policy if exists pulse_queue_events_mike_select on public.pulse_queue_events;
create policy pulse_queue_events_mike_select on public.pulse_queue_events
  for select to authenticated using (public.is_pulse_owner());

drop policy if exists pulse_continuation_runs_mike_select on public.pulse_continuation_runs;
create policy pulse_continuation_runs_mike_select on public.pulse_continuation_runs
  for select to authenticated using (public.is_pulse_owner());

create or replace function public.pulse_queue_contract_hash(c public.pulse_cards)
returns text
language sql
immutable
set search_path = public
as $$
  select md5(concat_ws('|',
    coalesce(c.contract_version::text, ''),
    coalesce(c.gate_contract::text, ''),
    coalesce(c.continuation_contract::text, ''),
    coalesce(c.payload::text, ''),
    coalesce(c.priority_band::text, ''),
    coalesce(c.priority_reason, ''),
    coalesce(c.deadline_at::text, ''),
    coalesce(c.blocked_work_count::text, ''),
    coalesce(c.mission_lane, ''),
    coalesce(c.dedupe_key, '')
  ));
$$;

create or replace function public.pulse_queue_base_errors(c public.pulse_cards)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  errors jsonb := '[]'::jsonb;
  target jsonb;
  action jsonb;
  action_target jsonb;
begin
  if c.contract_version is distinct from 1 then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'contract_version'));
  end if;
  if c.type = 'brief' then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'brief_ineligible'));
  elsif c.type not in ('action', 'decision', 'verdict') then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'card_type_ineligible'));
  end if;
  if nullif(btrim(c.dedupe_key), '') is null then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'dedupe_key_required'));
  end if;
  if c.priority_band is null or c.priority_band not between 0 and 3 then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'priority_band_invalid'));
  end if;
  if nullif(btrim(c.priority_reason), '') is null then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'priority_reason_required'));
  end if;
  if c.blocked_work_count is null or c.blocked_work_count < 0 then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'blocked_work_count_invalid'));
  end if;

  if coalesce((c.gate_contract->>'version')::integer, 0) <> 1 then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_contract_version'));
  end if;
  if coalesce(c.gate_contract->>'kind', '') not in ('authentication', 'consent', 'money', 'judgment') then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_kind'));
  end if;
  if nullif(btrim(c.gate_contract->>'reason_only_mike'), '') is null then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_reason_missing'));
  end if;
  if coalesce((c.gate_contract->>'estimated_human_seconds')::integer, 0) < 1 then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_estimate_invalid'));
  end if;
  target := c.gate_contract->'target';
  if coalesce(target->>'surface', '') not in ('pulse', 'web') then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_target_surface'));
  end if;
  if nullif(btrim(target->>'label'), '') is null then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_target_label'));
  end if;
  if target->>'surface' = 'web' and (
      coalesce(target->>'url', '') !~ '^https://[^/]+' or
      nullif(btrim(target->>'ref'), '') is null) then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_target_web_invalid'));
  end if;
  if c.gate_contract->>'kind' = 'money' and (
      jsonb_typeof(c.gate_contract->'money') is distinct from 'object' or
      nullif(c.gate_contract->'money'->>'amount', '') is null or
      (c.gate_contract->'money'->>'amount')::numeric < 0 or
      coalesce(c.gate_contract->'money'->>'currency', '') !~ '^[A-Z]{3}$' or
      nullif(btrim(c.gate_contract->'money'->>'payee'), '') is null or
      nullif(c.gate_contract->'money'->>'maximum_authorized_amount', '') is null or
      (c.gate_contract->'money'->>'maximum_authorized_amount')::numeric <
        (c.gate_contract->'money'->>'amount')::numeric) then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'money_terms_invalid'));
  end if;

  if coalesce((c.continuation_contract->>'version')::integer, 0) <> 1 then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'continuation_contract_version'));
  end if;
  if nullif(btrim(c.continuation_contract->>'owner_ref'), '') is null then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'continuation_owner_missing'));
  end if;
  if coalesce(c.continuation_contract->>'trigger', '') not in ('gate_answered', 'actions_verified') then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'continuation_trigger_invalid'));
  end if;
  if c.continuation_contract->>'operation' is distinct from 'resume_card_owner' then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'continuation_operation_invalid'));
  end if;
  if nullif(btrim(c.continuation_contract->>'correlation_key'), '') is null then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'continuation_correlation_missing'));
  end if;
  if coalesce(c.continuation_contract->'verification'->>'kind', '') not in
      ('owner_acknowledged', 'external_state', 'artifact_state') then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'continuation_verifier_invalid'));
  end if;
  if nullif(btrim(c.continuation_contract->>'success_message'), '') is null then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'continuation_success_missing'));
  end if;

  if c.type = 'action' then
    if c.gate_contract->>'kind' not in ('authentication', 'consent') or
        target->>'surface' is distinct from 'web' or
        c.continuation_contract->>'trigger' is distinct from 'actions_verified' then
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'action_gate_contract_mismatch'));
    end if;
    if coalesce((c.payload->>'actions_version')::integer, 0) <> 1 or
        jsonb_typeof(c.payload->'actions') is distinct from 'array' then
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'typed_action_required'));
    elsif jsonb_array_length(c.payload->'actions') = 0 then
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'typed_action_required'));
    else
      for action in select value from jsonb_array_elements(c.payload->'actions') loop
        -- Queue v1 accepts only operations already reviewed by the canonical
        -- pulse-mac-bridge registry. Generic recipe/path/selector operations
        -- and the legacy yeshie_task button never satisfy eligibility.
        if action->>'executor' is distinct from 'workflow' or
            coalesce(action->>'operation', '') not in
              ('gdoc_bridge_authorize', 'github_accept_org_invite') then
          errors := errors || jsonb_build_array(jsonb_build_object(
            'code', 'unsupported_operation',
            'detail', concat_ws('/', action->>'executor', action->>'operation')));
        end if;
        if coalesce((action->>'revision')::integer, 0) < 1 or
            jsonb_typeof(action->'params') is distinct from 'object' then
          errors := errors || jsonb_build_array(jsonb_build_object('code', 'typed_action_invalid'));
        end if;
        if action->'completion'->>'mode' is distinct from 'verified' or
            nullif(btrim(action->'completion'->>'success_message'), '') is null then
          errors := errors || jsonb_build_array(jsonb_build_object('code', 'unverified_completion'));
        end if;
        action_target := action->'human_gate'->'target';
        if nullif(btrim(action->'human_gate'->>'instruction'), '') is null then
          errors := errors || jsonb_build_array(jsonb_build_object('code', 'action_human_gate_required'));
        end if;
        if action->>'operation' = 'gdoc_bridge_authorize' then
          if action->'verification'->>'kind' is distinct from 'google_drive_about' then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'unsupported_verification'));
          end if;
          if action_target->>'ref' is distinct from 'google.oauth.consent.primary' or
              coalesce(action_target->>'url', '') !~ '^https://accounts[.]google[.]com/' then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'unsupported_gate_target'));
          end if;
        elsif action->>'operation' = 'github_accept_org_invite' then
          if action->'verification'->>'kind' is distinct from 'github_org_membership' then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'unsupported_verification'));
          end if;
          if jsonb_typeof(action->'params') is distinct from 'object' then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'github_invitation_contract_invalid'));
          elsif (select count(*) from jsonb_object_keys(action->'params')) <> 2 or
                coalesce(action->'params'->>'org', '') !~ '^[A-Za-z0-9]([A-Za-z0-9-]{0,37}[A-Za-z0-9])?$' or
                coalesce(action->'params'->>'username', '') !~ '^[A-Za-z0-9]([A-Za-z0-9-]{0,37}[A-Za-z0-9])?$' then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'github_invitation_contract_invalid'));
          end if;
          if action_target->>'ref' is distinct from 'github.org_invitation.accept' or
              action_target->>'url' is distinct from
                format('https://github.com/orgs/%s/invitation', action->'params'->>'org') then
            errors := errors || jsonb_build_array(jsonb_build_object('code', 'unsupported_gate_target'));
          end if;
        end if;
        if target->>'ref' is distinct from action_target->>'ref' or
            target->>'label' is distinct from action_target->>'label' then
          errors := errors || jsonb_build_array(jsonb_build_object('code', 'gate_target_mismatch'));
        end if;
      end loop;
    end if;
  elsif c.type in ('decision', 'verdict') then
    if c.gate_contract->>'kind' is distinct from 'judgment' or
        target->>'surface' is distinct from 'pulse' or
        c.continuation_contract->>'trigger' is distinct from 'gate_answered' then
      errors := errors || jsonb_build_array(jsonb_build_object('code', 'pulse_judgment_gate_required'));
    end if;
    if c.type = 'decision' then
      if jsonb_typeof(c.payload->'options') is distinct from 'array' then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'decision_options_incomplete'));
      elsif jsonb_array_length(c.payload->'options') < 2 then
        errors := errors || jsonb_build_array(jsonb_build_object('code', 'decision_options_incomplete'));
      end if;
    end if;
  end if;

  return errors;
exception
  when invalid_text_representation or numeric_value_out_of_range then
    return errors || jsonb_build_array(jsonb_build_object('code', 'contract_scalar_invalid'));
end;
$$;

create or replace function public.pulse_queue_contract_errors(c public.pulse_cards)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  errors jsonb := public.pulse_queue_base_errors(c);
begin
  if c.status <> 'open' then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'card_not_open'));
  end if;
  if c.snoozed_until is not null and c.snoozed_until > now() then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'card_snoozed'));
  end if;
  if nullif(btrim(c.dedupe_key), '') is not null and exists (
    select 1
    from public.pulse_cards other
    where other.app_id = c.app_id
      and other.id <> c.id
      and other.status = 'open'
      and other.queue_state <> 'legacy'
      and other.dedupe_key = c.dedupe_key
      and (other.snoozed_until is null or other.snoozed_until <= now())
      and public.pulse_queue_base_errors(other) = '[]'::jsonb
      and (coalesce(other.eligible_at, other.created_at), other.id) <
          (coalesce(c.eligible_at, c.created_at), c.id)
  ) then
    errors := errors || jsonb_build_array(jsonb_build_object('code', 'duplicate_gate'));
  end if;
  return errors;
end;
$$;

create or replace function public.reconcile_pulse_queue()
returns table(card_id uuid, queue_position smallint, overflow_count bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
-- Out-params (card_id, queue_position) shadow column names used throughout
-- the body; without this pragma the first statement fails with "column
-- reference is ambiguous" at runtime (caught on the 2026-08-01 shadow run).
#variable_conflict use_column
begin
  -- Re-entrancy guard: a direct (depth-0) call's own UPDATEs fire the
  -- statement triggers at depth 1, which the pg_trigger_depth() > 1 trigger
  -- guard does NOT stop; without this the inner call truncates
  -- pulse_queue_before while the outer call still needs it for event diffs.
  if coalesce(current_setting('pulse_zero.reconcile_active', true), '') = '1' then
    return;
  end if;
  perform set_config('pulse_zero.reconcile_active', '1', true);

  perform pg_advisory_xact_lock(hashtextextended('pulse-zero:queue-v1', 0));

  create temporary table if not exists pulse_queue_before (
    card_id uuid primary key,
    queue_state text,
    queue_position smallint
  ) on commit drop;
  -- Clear the per-transaction snapshot. Deliberately `delete ... where true`,
  -- not `truncate`: same effect on this tiny temp table, and both truncate
  -- and bare delete trip destructive-command guards (dcg) for anyone
  -- applying this file.
  delete from pulse_queue_before where true;
  insert into pulse_queue_before(card_id, queue_state, queue_position)
    select id, queue_state, queue_position
    from public.pulse_cards
    where app_id = 'pulse-zero' and queue_state <> 'legacy';

  update public.pulse_cards c
  set eligibility_errors = public.pulse_queue_contract_errors(c),
      contract_hash = public.pulse_queue_contract_hash(c)
  where c.app_id = 'pulse-zero' and c.queue_state <> 'legacy';

  update public.pulse_cards c
  set queue_state = case when c.eligibility_errors = '[]'::jsonb then 'eligible' else 'hold' end,
      queue_position = null,
      eligible_at = case
        when c.eligibility_errors = '[]'::jsonb then coalesce(c.eligible_at, now())
        else c.eligible_at
      end
  where c.app_id = 'pulse-zero' and c.queue_state <> 'legacy';

  with ranked as (
    select c.id,
      row_number() over (order by
        c.priority_band asc,
        c.deadline_at asc nulls last,
        case
          when lower(coalesce(c.mission_lane, '')) = 'legends' then 0
          when lower(coalesce(c.mission_lane, '')) in ('playmaker', 'playwriting') then 1
          when lower(coalesce(c.mission_lane, '')) = 'soma' or
               lower(coalesce(c.mission_lane, '')) like 'soma-%' then 2
          else 3
        end asc,
        c.blocked_work_count desc,
        c.eligible_at asc,
        c.id asc
      )::smallint as position
    from public.pulse_cards c
    where c.app_id = 'pulse-zero'
      and c.queue_state = 'eligible'
      and c.status = 'open'
      and (c.snoozed_until is null or c.snoozed_until <= now())
      and c.eligibility_errors = '[]'::jsonb
    order by
      c.priority_band asc,
      c.deadline_at asc nulls last,
      case
        when lower(coalesce(c.mission_lane, '')) = 'legends' then 0
        when lower(coalesce(c.mission_lane, '')) in ('playmaker', 'playwriting') then 1
        when lower(coalesce(c.mission_lane, '')) = 'soma' or
             lower(coalesce(c.mission_lane, '')) like 'soma-%' then 2
        else 3
      end asc,
      c.blocked_work_count desc,
      c.eligible_at asc,
      c.id asc
    limit 5
  )
  update public.pulse_cards c
  set queue_state = 'queued', queue_position = ranked.position
  from ranked
  where c.id = ranked.id;

  insert into public.pulse_queue_events(
    card_id, event_type, from_state, to_state, from_position, to_position,
    reason, actor, contract_hash
  )
  select c.id,
    case
      when b.queue_position is null and c.queue_position is not null then 'promoted'
      when b.queue_position is not null and c.queue_position is null then 'released'
      when b.queue_position is distinct from c.queue_position then 'moved'
      when b.queue_state is distinct from c.queue_state then 'state_changed'
      else 'unchanged'
    end,
    b.queue_state, c.queue_state, b.queue_position, c.queue_position,
    jsonb_build_object('eligibility_errors', c.eligibility_errors),
    'queue_reconciler', c.contract_hash
  from public.pulse_cards c
  join pulse_queue_before b on b.card_id = c.id
  where b.queue_state is distinct from c.queue_state
     or b.queue_position is distinct from c.queue_position;

  -- Reset before returning so a later reconcile in the same transaction
  -- still runs; a skipped re-entrant call returns no rows, which trigger
  -- invocations ignore.
  perform set_config('pulse_zero.reconcile_active', '', true);

  return query
  select c.id, c.queue_position,
    (select count(*) from public.pulse_cards e
      where e.app_id = 'pulse-zero' and e.queue_state = 'eligible'
        and e.status = 'open' and e.eligibility_errors = '[]'::jsonb
        and (e.snoozed_until is null or e.snoozed_until <= now()))
  from public.pulse_cards c
  where c.app_id = 'pulse-zero' and c.queue_state = 'queued'
  order by c.queue_position;
end;
$$;

create or replace function public.pulse_reconcile_after_card_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if pg_trigger_depth() > 1 then return null; end if;
  perform public.reconcile_pulse_queue();
  return null;
end;
$$;

drop trigger if exists pulse_queue_reconcile_insert on public.pulse_cards;
create trigger pulse_queue_reconcile_insert
  after insert on public.pulse_cards
  for each statement execute function public.pulse_reconcile_after_card_change();

drop trigger if exists pulse_queue_reconcile_update on public.pulse_cards;
create trigger pulse_queue_reconcile_update
  after update of status, snoozed_until, payload, contract_version, gate_contract,
    continuation_contract, queue_state, priority_band, priority_reason,
    deadline_at, blocked_work_count, mission_lane, eligible_at, dedupe_key
  on public.pulse_cards
  for each statement execute function public.pulse_reconcile_after_card_change();

create or replace view public.pulse_active_queue_v1
with (security_invoker = true)
as
select c.*,
  (select count(*) from public.pulse_cards e
    where e.app_id = c.app_id and e.queue_state = 'eligible'
      and e.status = 'open' and e.eligibility_errors = '[]'::jsonb
      and (e.snoozed_until is null or e.snoozed_until <= now())) as ready_behind_count
from public.pulse_cards c
where c.app_id = 'pulse-zero'
  and c.status = 'open'
  and c.queue_state = 'queued'
  and c.queue_position between 1 and 5
  and c.eligibility_errors = '[]'::jsonb
  and (c.snoozed_until is null or c.snoozed_until <= now());

-- Queue-v1 action buttons send identifiers only. This function re-reads the
-- reviewed action from the queued card and constructs the complete command;
-- browser-supplied executor payloads never cross this boundary.
create or replace function public.enqueue_pulse_action(
  p_card_id uuid,
  p_action_id text,
  p_revision integer,
  p_attempt integer default 1
)
returns table(
  id bigint,
  status text,
  result jsonb,
  pulse_card_id uuid,
  pulse_action_id text,
  pulse_revision integer,
  attempt integer,
  idempotency_key text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
-- RETURNS TABLE declares out-params (idempotency_key, status, attempt) that
-- shadow mac_commands columns; resolve unqualified names to columns so the
-- ON CONFLICT index predicate is unambiguous.
#variable_conflict use_column
declare
  v_card public.pulse_cards%rowtype;
  v_action jsonb;
  v_key text;
  v_id bigint;
begin
  if auth.role() <> 'service_role' and not public.is_pulse_owner() then
    raise exception 'Pulse owner authentication required' using errcode = '42501';
  end if;
  if p_attempt < 1 then raise exception 'attempt must be positive' using errcode = '22023'; end if;

  select * into v_card from public.pulse_cards
  where pulse_cards.id = p_card_id and app_id = 'pulse-zero'
  for update;
  if not found then raise exception 'card not found' using errcode = 'P0002'; end if;
  if v_card.status <> 'open' or v_card.queue_state <> 'queued' or
      v_card.queue_position not between 1 and 5 or
      (v_card.snoozed_until is not null and v_card.snoozed_until > now()) then
    raise exception 'card is not in the active queue' using errcode = '22023';
  end if;
  if v_card.contract_hash is distinct from public.pulse_queue_contract_hash(v_card) or
      public.pulse_queue_contract_errors(v_card) <> '[]'::jsonb then
    raise exception 'card contract changed or is invalid; reconcile first' using errcode = '22023';
  end if;

  select value into v_action
  from jsonb_array_elements(v_card.payload->'actions')
  where value->>'id' = p_action_id
  limit 1;
  if v_action is null then raise exception 'action not found' using errcode = 'P0002'; end if;
  if coalesce((v_action->>'revision')::integer, 0) <> p_revision then
    raise exception 'stale action revision' using errcode = '22023';
  end if;
  if v_action->>'executor' is distinct from 'workflow' or not (
      (v_action->>'operation' = 'gdoc_bridge_authorize' and
       v_action->'verification'->>'kind' = 'google_drive_about' and
       v_action->'human_gate'->'target'->>'ref' = 'google.oauth.consent.primary') or
      (v_action->>'operation' = 'github_accept_org_invite' and
       v_action->'verification'->>'kind' = 'github_org_membership' and
       v_action->'human_gate'->'target'->>'ref' = 'github.org_invitation.accept')
    ) then
    raise exception 'action operation is not reviewed' using errcode = '22023';
  end if;

  v_key := format('pulse-zero:%s:%s:r%s:a%s', p_card_id, p_action_id, p_revision, p_attempt);
  insert into public.mac_commands(
    command, payload, status, pulse_card_id, pulse_action_id,
    pulse_revision, attempt, idempotency_key
  ) values (
    'execute_card_action',
    jsonb_build_object(
      'contract_version', 1,
      'card_id', p_card_id,
      'action_id', p_action_id,
      'revision', p_revision,
      'idempotency_key', v_key,
      'action', v_action
    ),
    'open', p_card_id, p_action_id, p_revision, p_attempt, v_key
  )
  on conflict (idempotency_key) where idempotency_key is not null do nothing
  returning mac_commands.id into v_id;

  if v_id is null then
    select mac_commands.id into v_id from public.mac_commands
    where mac_commands.idempotency_key = v_key;
  end if;

  return query
  select m.id, m.status, m.result, m.pulse_card_id, m.pulse_action_id,
    m.pulse_revision, m.attempt, m.idempotency_key, m.created_at
  from public.mac_commands m where m.id = v_id;
end;
$$;

create or replace function public.start_pulse_continuation_v1(
  p_card_id uuid,
  p_command_id bigint
)
returns setof public.pulse_continuation_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_card public.pulse_cards%rowtype;
  v_command public.mac_commands%rowtype;
  v_id bigint;
begin
  if auth.role() <> 'service_role' and not public.is_pulse_owner() then
    raise exception 'Pulse owner authentication required' using errcode = '42501';
  end if;
  select * into v_card from public.pulse_cards
    where id = p_card_id and app_id = 'pulse-zero' for update;
  select * into v_command from public.mac_commands where id = p_command_id;
  if v_card.id is null or v_command.id is null or v_card.status <> 'open' or
      v_card.queue_state <> 'queued' or v_command.pulse_card_id <> v_card.id or
      v_command.status <> 'done' or coalesce((v_command.result->>'verified')::boolean, false) is not true then
    raise exception 'verified queued action receipt required' using errcode = '22023';
  end if;
  if v_card.continuation_contract->>'trigger' is distinct from 'actions_verified' then
    raise exception 'continuation trigger mismatch' using errcode = '22023';
  end if;

  insert into public.pulse_continuation_runs(
    card_id, command_id, owner_ref, correlation_key, verifier_kind, safe_message
  ) values (
    v_card.id,
    v_command.id,
    v_card.continuation_contract->>'owner_ref',
    v_card.continuation_contract->>'correlation_key',
    v_card.continuation_contract->'verification'->>'kind',
    'The team is resuming the blocked work.'
  )
  on conflict (card_id, command_id) do nothing
  returning id into v_id;
  if v_id is null then
    select id into v_id from public.pulse_continuation_runs
      where card_id = p_card_id and command_id = p_command_id;
  end if;
  return query select * from public.pulse_continuation_runs where id = v_id;
end;
$$;

-- Direct Pulse judgment is itself the human gate. Record the answer but keep
-- the card visible until its owner acknowledges or the named verifier passes.
create or replace function public.answer_pulse_gate_v1(
  p_card_id uuid,
  p_answer jsonb
)
returns setof public.pulse_continuation_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_card public.pulse_cards%rowtype;
  v_id bigint;
begin
  if auth.role() <> 'service_role' and not public.is_pulse_owner() then
    raise exception 'Pulse owner authentication required' using errcode = '42501';
  end if;
  if jsonb_typeof(p_answer) is distinct from 'object' or
      nullif(btrim(p_answer->>'action_id'), '') is null or
      length(coalesce(p_answer::text, '')) > 2000 then
    raise exception 'a bounded structured answer is required' using errcode = '22023';
  end if;
  select * into v_card from public.pulse_cards
    where id = p_card_id and app_id = 'pulse-zero' for update;
  if v_card.id is null or v_card.status <> 'open' or v_card.queue_state <> 'queued' or
      v_card.gate_contract->>'kind' is distinct from 'judgment' or
      v_card.gate_contract->'target'->>'surface' is distinct from 'pulse' or
      v_card.continuation_contract->>'trigger' is distinct from 'gate_answered' then
    raise exception 'active Pulse judgment gate required' using errcode = '22023';
  end if;
  if v_card.type = 'decision' and not (
      (p_answer->>'action_id' = 'opt' and
       coalesce(v_card.payload->'options', '[]'::jsonb) ? (p_answer->>'value')) or
      (p_answer->>'action_id' = 'other' and nullif(btrim(p_answer->>'value'), '') is not null)
    ) then
    raise exception 'answer is not one of the reviewed decision options' using errcode = '22023';
  end if;
  if v_card.type = 'verdict' and coalesce(p_answer->>'action_id', '') not in
      ('accept', 'change', 'retire') then
    raise exception 'answer is not a reviewed verdict action' using errcode = '22023';
  end if;

  select id into v_id from public.pulse_continuation_runs
    where card_id = p_card_id and command_id is null;
  if v_id is not null then
    return query select * from public.pulse_continuation_runs where id = v_id;
    return;
  end if;

  update public.pulse_cards
    set answer = p_answer, answered_at = now()
    where id = v_card.id;
  insert into public.pulse_continuation_runs(
    card_id, command_id, owner_ref, correlation_key, verifier_kind, safe_message
  ) values (
    v_card.id,
    null,
    v_card.continuation_contract->>'owner_ref',
    v_card.continuation_contract->>'correlation_key',
    v_card.continuation_contract->'verification'->>'kind',
    'The team is resuming the blocked work.'
  )
  on conflict (card_id) where command_id is null do nothing
  returning id into v_id;
  if v_id is null then
    select id into v_id from public.pulse_continuation_runs
      where card_id = p_card_id and command_id is null;
  end if;
  return query select * from public.pulse_continuation_runs where id = v_id;
end;
$$;

-- Worker-only acknowledgment. Owner acknowledgment is the v1 minimum; callers
-- should use external/artifact verification when the continuation contract names it.
create or replace function public.acknowledge_pulse_continuation_v1(
  p_run_id bigint,
  p_verified boolean,
  p_safe_message text,
  p_verification_summary text
)
returns public.pulse_continuation_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.pulse_continuation_runs%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if length(coalesce(p_safe_message, '')) > 500 or length(coalesce(p_verification_summary, '')) > 1000 then
    raise exception 'safe continuation result is too long' using errcode = '22023';
  end if;
  update public.pulse_continuation_runs
  set status = case when p_verified then 'succeeded' else 'failed' end,
      safe_message = coalesce(nullif(p_safe_message, ''),
        case when p_verified then 'Blocked work resumed.' else 'The team could not verify the continuation.' end),
      verification_summary = nullif(p_verification_summary, ''),
      updated_at = now()
  where id = p_run_id and status in ('queued', 'running', 'verifying')
  returning * into v_run;
  if v_run.id is null then raise exception 'active continuation not found' using errcode = 'P0002'; end if;

  if p_verified then
    update public.pulse_cards
    set status = 'resolved',
        resolved_note = coalesce(nullif(p_safe_message, ''), continuation_contract->>'success_message'),
        answered_at = now()
    where id = v_run.card_id and status = 'open';
  end if;
  return v_run;
end;
$$;

revoke all on public.pulse_queue_events from anon, authenticated;
revoke all on public.pulse_continuation_runs from anon, authenticated;
grant select on public.pulse_queue_events to authenticated;
grant select on public.pulse_continuation_runs to authenticated;
grant select on public.pulse_active_queue_v1 to authenticated;
revoke all on function public.reconcile_pulse_queue() from public;
revoke all on function public.enqueue_pulse_action(uuid, text, integer, integer) from public;
revoke all on function public.start_pulse_continuation_v1(uuid, bigint) from public;
revoke all on function public.answer_pulse_gate_v1(uuid, jsonb) from public;
revoke all on function public.acknowledge_pulse_continuation_v1(bigint, boolean, text, text) from public;
grant execute on function public.enqueue_pulse_action(uuid, text, integer, integer) to authenticated, service_role;
grant execute on function public.start_pulse_continuation_v1(uuid, bigint) to authenticated, service_role;
grant execute on function public.answer_pulse_gate_v1(uuid, jsonb) to authenticated, service_role;
grant execute on function public.acknowledge_pulse_continuation_v1(bigint, boolean, text, text) to service_role;
grant execute on function public.reconcile_pulse_queue() to service_role;

-- Deliberately no pg_cron schedule is created here. After shadow review and
-- explicit automation approval, a service-role steward may call
-- reconcile_pulse_queue() once per minute so expired snoozes re-enter. The
-- insert/update triggers provide deterministic reconciliation meanwhile.

comment on view public.pulse_active_queue_v1 is
  'Feature-flagged server-ranked Pulse queue. Legacy rows are excluded by queue_state.';
comment on function public.enqueue_pulse_action(uuid, text, integer, integer) is
  'Constructs execute_card_action from the stored queued card; accepts identifiers, never a browser action payload.';
